production:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017
